//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Setting/InputSystem/Esc.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Esc: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Esc()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Esc"",
    ""maps"": [
        {
            ""name"": ""callSetting"",
            ""id"": ""b3df5833-6c59-429e-8290-243cef035a7d"",
            ""actions"": [
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""940d553d-7f7f-40a2-adb6-e412e915c2e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""37222c55-408c-43e8-a270-f70569a611b1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // callSetting
        m_callSetting = asset.FindActionMap("callSetting", throwIfNotFound: true);
        m_callSetting_Esc = m_callSetting.FindAction("Esc", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // callSetting
    private readonly InputActionMap m_callSetting;
    private List<ICallSettingActions> m_CallSettingActionsCallbackInterfaces = new List<ICallSettingActions>();
    private readonly InputAction m_callSetting_Esc;
    public struct CallSettingActions
    {
        private @Esc m_Wrapper;
        public CallSettingActions(@Esc wrapper) { m_Wrapper = wrapper; }
        public InputAction @Esc => m_Wrapper.m_callSetting_Esc;
        public InputActionMap Get() { return m_Wrapper.m_callSetting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CallSettingActions set) { return set.Get(); }
        public void AddCallbacks(ICallSettingActions instance)
        {
            if (instance == null || m_Wrapper.m_CallSettingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CallSettingActionsCallbackInterfaces.Add(instance);
            @Esc.started += instance.OnEsc;
            @Esc.performed += instance.OnEsc;
            @Esc.canceled += instance.OnEsc;
        }

        private void UnregisterCallbacks(ICallSettingActions instance)
        {
            @Esc.started -= instance.OnEsc;
            @Esc.performed -= instance.OnEsc;
            @Esc.canceled -= instance.OnEsc;
        }

        public void RemoveCallbacks(ICallSettingActions instance)
        {
            if (m_Wrapper.m_CallSettingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICallSettingActions instance)
        {
            foreach (var item in m_Wrapper.m_CallSettingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CallSettingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CallSettingActions @callSetting => new CallSettingActions(this);
    public interface ICallSettingActions
    {
        void OnEsc(InputAction.CallbackContext context);
    }
}
